// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	GameMoves   string
	GamePlayers string
	Games       string
	Users       string
}{
	GameMoves:   "game_moves",
	GamePlayers: "game_players",
	Games:       "games",
	Users:       "users",
}
