// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/grpc/game/game.proto

package gamepb

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State int32

const (
	State_S_UNKNOWN  State = 0
	State_S_CREATED  State = 1
	State_S_ACTIVE   State = 2
	State_S_FINISHED State = 3
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "S_UNKNOWN",
		1: "S_CREATED",
		2: "S_ACTIVE",
		3: "S_FINISHED",
	}
	State_value = map[string]int32{
		"S_UNKNOWN":  0,
		"S_CREATED":  1,
		"S_ACTIVE":   2,
		"S_FINISHED": 3,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_game_game_proto_enumTypes[0].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_api_grpc_game_game_proto_enumTypes[0]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{0}
}

type Type int32

const (
	Type_T_UNKNOWN     Type = 0
	Type_T_TIC_TAC_TOE Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "T_UNKNOWN",
		1: "T_TIC_TAC_TOE",
	}
	Type_value = map[string]int32{
		"T_UNKNOWN":     0,
		"T_TIC_TAC_TOE": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_game_game_proto_enumTypes[1].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_api_grpc_game_game_proto_enumTypes[1]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{1}
}

type UnitCode int32

const (
	UnitCode_UC_UNKNOWN       UnitCode = 0
	UnitCode_UC_TIC_TAC_TOE_X UnitCode = 1
	UnitCode_UC_TIC_TAC_TOE_O UnitCode = 2
)

// Enum value maps for UnitCode.
var (
	UnitCode_name = map[int32]string{
		0: "UC_UNKNOWN",
		1: "UC_TIC_TAC_TOE_X",
		2: "UC_TIC_TAC_TOE_O",
	}
	UnitCode_value = map[string]int32{
		"UC_UNKNOWN":       0,
		"UC_TIC_TAC_TOE_X": 1,
		"UC_TIC_TAC_TOE_O": 2,
	}
)

func (x UnitCode) Enum() *UnitCode {
	p := new(UnitCode)
	*p = x
	return p
}

func (x UnitCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnitCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_game_game_proto_enumTypes[2].Descriptor()
}

func (UnitCode) Type() protoreflect.EnumType {
	return &file_api_grpc_game_game_proto_enumTypes[2]
}

func (x UnitCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnitCode.Descriptor instead.
func (UnitCode) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{2}
}

type StreamAction int32

const (
	StreamAction_SA_UNKNOWN           StreamAction = 0
	StreamAction_SA_PLAYER_CONNECT    StreamAction = 1
	StreamAction_SA_PLAYER_READY      StreamAction = 2
	StreamAction_SA_PLAYER_MOVE       StreamAction = 3
	StreamAction_SA_PLAYER_TIMEOUT    StreamAction = 4
	StreamAction_SA_PLAYER_DRAW       StreamAction = 5
	StreamAction_SA_PLAYER_GAVE_UP    StreamAction = 6
	StreamAction_SA_PLAYER_DISCONNECT StreamAction = 7
	StreamAction_SA_GAME_START        StreamAction = 8
	StreamAction_SA_GAME_FINISH       StreamAction = 9
)

// Enum value maps for StreamAction.
var (
	StreamAction_name = map[int32]string{
		0: "SA_UNKNOWN",
		1: "SA_PLAYER_CONNECT",
		2: "SA_PLAYER_READY",
		3: "SA_PLAYER_MOVE",
		4: "SA_PLAYER_TIMEOUT",
		5: "SA_PLAYER_DRAW",
		6: "SA_PLAYER_GAVE_UP",
		7: "SA_PLAYER_DISCONNECT",
		8: "SA_GAME_START",
		9: "SA_GAME_FINISH",
	}
	StreamAction_value = map[string]int32{
		"SA_UNKNOWN":           0,
		"SA_PLAYER_CONNECT":    1,
		"SA_PLAYER_READY":      2,
		"SA_PLAYER_MOVE":       3,
		"SA_PLAYER_TIMEOUT":    4,
		"SA_PLAYER_DRAW":       5,
		"SA_PLAYER_GAVE_UP":    6,
		"SA_PLAYER_DISCONNECT": 7,
		"SA_GAME_START":        8,
		"SA_GAME_FINISH":       9,
	}
)

func (x StreamAction) Enum() *StreamAction {
	p := new(StreamAction)
	*p = x
	return p
}

func (x StreamAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamAction) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_game_game_proto_enumTypes[3].Descriptor()
}

func (StreamAction) Type() protoreflect.EnumType {
	return &file_api_grpc_game_game_proto_enumTypes[3]
}

func (x StreamAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamAction.Descriptor instead.
func (StreamAction) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{3}
}

type FinishReason int32

const (
	FinishReason_FR_UNKNOWN FinishReason = 0
	FinishReason_FR_DEFAULT FinishReason = 1
	FinishReason_FR_DRAW    FinishReason = 2
	FinishReason_FR_GAVE_UP FinishReason = 3
	FinishReason_FR_INVALID FinishReason = 4
)

// Enum value maps for FinishReason.
var (
	FinishReason_name = map[int32]string{
		0: "FR_UNKNOWN",
		1: "FR_DEFAULT",
		2: "FR_DRAW",
		3: "FR_GAVE_UP",
		4: "FR_INVALID",
	}
	FinishReason_value = map[string]int32{
		"FR_UNKNOWN": 0,
		"FR_DEFAULT": 1,
		"FR_DRAW":    2,
		"FR_GAVE_UP": 3,
		"FR_INVALID": 4,
	}
)

func (x FinishReason) Enum() *FinishReason {
	p := new(FinishReason)
	*p = x
	return p
}

func (x FinishReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinishReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_grpc_game_game_proto_enumTypes[4].Descriptor()
}

func (FinishReason) Type() protoreflect.EnumType {
	return &file_api_grpc_game_game_proto_enumTypes[4]
}

func (x FinishReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinishReason.Descriptor instead.
func (FinishReason) EnumDescriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{4}
}

type CreateGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitiatorId string  `protobuf:"bytes,1,opt,name=initiator_id,json=initiatorId,proto3" json:"initiator_id,omitempty"`
	Type        Type    `protobuf:"varint,2,opt,name=type,proto3,enum=game.Type" json:"type,omitempty"`
	Bid         float64 `protobuf:"fixed64,3,opt,name=bid,proto3" json:"bid,omitempty"`
	MaxPlayers  int32   `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGameRequest) GetInitiatorId() string {
	if x != nil {
		return x.InitiatorId
	}
	return ""
}

func (x *CreateGameRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_T_UNKNOWN
}

func (x *CreateGameRequest) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *CreateGameRequest) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

type GameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         Type                  `protobuf:"varint,2,opt,name=type,proto3,enum=game.Type" json:"type,omitempty"`
	StateCode    State                 `protobuf:"varint,3,opt,name=state_code,json=stateCode,proto3,enum=game.State" json:"state_code,omitempty"`
	Bid          float64               `protobuf:"fixed64,4,opt,name=bid,proto3" json:"bid,omitempty"`
	MaxPlayers   int32                 `protobuf:"varint,5,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	FinishReason FinishReason          `protobuf:"varint,6,opt,name=finish_reason,json=finishReason,proto3,enum=game.FinishReason" json:"finish_reason,omitempty"`
	Players      []*GamePlayerResponse `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	CreatedAt    *timestamp.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt    *timestamp.Timestamp  `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt   *timestamp.Timestamp  `protobuf:"bytes,10,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{1}
}

func (x *GameResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameResponse) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_T_UNKNOWN
}

func (x *GameResponse) GetStateCode() State {
	if x != nil {
		return x.StateCode
	}
	return State_S_UNKNOWN
}

func (x *GameResponse) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *GameResponse) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *GameResponse) GetFinishReason() FinishReason {
	if x != nil {
		return x.FinishReason
	}
	return FinishReason_FR_UNKNOWN
}

func (x *GameResponse) GetPlayers() []*GamePlayerResponse {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameResponse) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GameResponse) GetStartedAt() *timestamp.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GameResponse) GetFinishedAt() *timestamp.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type GamePlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position int32  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *GamePlayerResponse) Reset() {
	*x = GamePlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GamePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlayerResponse) ProtoMessage() {}

func (x *GamePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlayerResponse.ProtoReflect.Descriptor instead.
func (*GamePlayerResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{2}
}

func (x *GamePlayerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GamePlayerResponse) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameId string       `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId string       `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action StreamAction `protobuf:"varint,3,opt,name=action,proto3,enum=game.StreamAction" json:"action,omitempty"`
	Data   *any1.Any    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRequest) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StreamRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamRequest) GetAction() StreamAction {
	if x != nil {
		return x.Action
	}
	return StreamAction_SA_UNKNOWN
}

func (x *StreamRequest) GetData() *any1.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok          bool         `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Description string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	GameId      string       `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	UserId      string       `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action      StreamAction `protobuf:"varint,5,opt,name=action,proto3,enum=game.StreamAction" json:"action,omitempty"`
	Data        *any1.Any    `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{4}
}

func (x *StreamResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StreamResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StreamResponse) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *StreamResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamResponse) GetAction() StreamAction {
	if x != nil {
		return x.Action
	}
	return StreamAction_SA_UNKNOWN
}

func (x *StreamResponse) GetData() *any1.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type StreamData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action StreamAction         `protobuf:"varint,1,opt,name=action,proto3,enum=game.StreamAction" json:"action,omitempty"`
	Data   *any1.Any            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Ts     *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *StreamData) Reset() {
	*x = StreamData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamData) ProtoMessage() {}

func (x *StreamData) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamData.ProtoReflect.Descriptor instead.
func (*StreamData) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{5}
}

func (x *StreamData) GetAction() StreamAction {
	if x != nil {
		return x.Action
	}
	return StreamAction_SA_UNKNOWN
}

func (x *StreamData) GetData() *any1.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamData) GetTs() *timestamp.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type GameStartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GameStartResponse) Reset() {
	*x = GameStartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStartResponse) ProtoMessage() {}

func (x *GameStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStartResponse.ProtoReflect.Descriptor instead.
func (*GameStartResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{6}
}

type PlayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *PlayerResponse) Reset() {
	*x = PlayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerResponse) ProtoMessage() {}

func (x *PlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerResponse.ProtoReflect.Descriptor instead.
func (*PlayerResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type PlayerMoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrikerId string              `protobuf:"bytes,1,opt,name=striker_id,json=strikerId,proto3" json:"striker_id,omitempty"`
	BatterId  string              `protobuf:"bytes,2,opt,name=batter_id,json=batterId,proto3" json:"batter_id,omitempty"`
	UnitCode  UnitCode            `protobuf:"varint,3,opt,name=unit_code,json=unitCode,proto3,enum=game.UnitCode" json:"unit_code,omitempty"`
	Position  *PlayerMovePosition `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *PlayerMoveResponse) Reset() {
	*x = PlayerMoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMoveResponse) ProtoMessage() {}

func (x *PlayerMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMoveResponse.ProtoReflect.Descriptor instead.
func (*PlayerMoveResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerMoveResponse) GetStrikerId() string {
	if x != nil {
		return x.StrikerId
	}
	return ""
}

func (x *PlayerMoveResponse) GetBatterId() string {
	if x != nil {
		return x.BatterId
	}
	return ""
}

func (x *PlayerMoveResponse) GetUnitCode() UnitCode {
	if x != nil {
		return x.UnitCode
	}
	return UnitCode_UC_UNKNOWN
}

func (x *PlayerMoveResponse) GetPosition() *PlayerMovePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

type PlayerMovePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	X     int32 `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y     int32 `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *PlayerMovePosition) Reset() {
	*x = PlayerMovePosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMovePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMovePosition) ProtoMessage() {}

func (x *PlayerMovePosition) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMovePosition.ProtoReflect.Descriptor instead.
func (*PlayerMovePosition) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerMovePosition) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *PlayerMovePosition) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerMovePosition) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FinishPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Profit   string `protobuf:"bytes,2,opt,name=profit,proto3" json:"profit,omitempty"`
	Fee      string `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	Draw     bool   `protobuf:"varint,4,opt,name=draw,proto3" json:"draw,omitempty"`
	GaveUp   bool   `protobuf:"varint,5,opt,name=gave_up,json=gaveUp,proto3" json:"gave_up,omitempty"`
}

func (x *FinishPlayer) Reset() {
	*x = FinishPlayer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPlayer) ProtoMessage() {}

func (x *FinishPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPlayer.ProtoReflect.Descriptor instead.
func (*FinishPlayer) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{10}
}

func (x *FinishPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *FinishPlayer) GetProfit() string {
	if x != nil {
		return x.Profit
	}
	return ""
}

func (x *FinishPlayer) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *FinishPlayer) GetDraw() bool {
	if x != nil {
		return x.Draw
	}
	return false
}

func (x *FinishPlayer) GetGaveUp() bool {
	if x != nil {
		return x.GaveUp
	}
	return false
}

type GameFinishResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason  FinishReason    `protobuf:"varint,1,opt,name=reason,proto3,enum=game.FinishReason" json:"reason,omitempty"`
	Players []*FinishPlayer `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *GameFinishResponse) Reset() {
	*x = GameFinishResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_game_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameFinishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameFinishResponse) ProtoMessage() {}

func (x *GameFinishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_game_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameFinishResponse.ProtoReflect.Descriptor instead.
func (*GameFinishResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_game_game_proto_rawDescGZIP(), []int{11}
}

func (x *GameFinishResponse) GetReason() FinishReason {
	if x != nil {
		return x.Reason
	}
	return FinishReason_FR_UNKNOWN
}

func (x *GameFinishResponse) GetPlayers() []*FinishPlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_api_grpc_game_game_proto protoreflect.FileDescriptor

var file_api_grpc_game_game_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a,
	0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61,
	0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x22, 0xbd, 0x03, 0x0a, 0x0c, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61,
	0x78, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x37, 0x0a, 0x0d, 0x66, 0x69, 0x6e, 0x69,
	0x73, 0x68, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x66,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x66, 0x69,
	0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x41, 0x74, 0x22, 0x40, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x0d, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xca, 0x01, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x8e, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x2a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02,
	0x74, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x0e, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x12, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x62, 0x61, 0x74, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x09, 0x75, 0x6e, 0x69,
	0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x75, 0x6e,
	0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x34, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x46, 0x0a, 0x12,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x76, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x79, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x65,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x66, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x72, 0x61, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x64, 0x72, 0x61, 0x77,
	0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x76, 0x65, 0x5f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x67, 0x61, 0x76, 0x65, 0x55, 0x70, 0x22, 0x6e, 0x0a, 0x12, 0x47, 0x61, 0x6d,
	0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x07, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x52, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x2a, 0x43, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x53, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x53, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x03, 0x2a, 0x28,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x5f, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x5f, 0x54, 0x49, 0x43, 0x5f, 0x54,
	0x41, 0x43, 0x5f, 0x54, 0x4f, 0x45, 0x10, 0x01, 0x2a, 0x46, 0x0a, 0x08, 0x55, 0x6e, 0x69, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x55, 0x43, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x43, 0x5f, 0x54, 0x49, 0x43, 0x5f, 0x54,
	0x41, 0x43, 0x5f, 0x54, 0x4f, 0x45, 0x5f, 0x58, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x43,
	0x5f, 0x54, 0x49, 0x43, 0x5f, 0x54, 0x41, 0x43, 0x5f, 0x54, 0x4f, 0x45, 0x5f, 0x4f, 0x10, 0x02,
	0x2a, 0xe1, 0x01, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x41, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x41, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x43,
	0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x41, 0x5f, 0x50,
	0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x02, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x41, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10,
	0x03, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x41, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x54,
	0x49, 0x4d, 0x45, 0x4f, 0x55, 0x54, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x41, 0x5f, 0x50,
	0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x44, 0x52, 0x41, 0x57, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11,
	0x53, 0x41, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x47, 0x41, 0x56, 0x45, 0x5f, 0x55,
	0x50, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x41, 0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52,
	0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x10, 0x07, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x41, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x08,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x41, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x5f, 0x46, 0x49, 0x4e, 0x49,
	0x53, 0x48, 0x10, 0x09, 0x2a, 0x5b, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x52, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55,
	0x4c, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x52, 0x5f, 0x44, 0x52, 0x41, 0x57, 0x10,
	0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x52, 0x5f, 0x47, 0x41, 0x56, 0x45, 0x5f, 0x55, 0x50, 0x10,
	0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x46, 0x52, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10,
	0x04, 0x32, 0x88, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x13, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09,
	0x2e, 0x2f, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_grpc_game_game_proto_rawDescOnce sync.Once
	file_api_grpc_game_game_proto_rawDescData = file_api_grpc_game_game_proto_rawDesc
)

func file_api_grpc_game_game_proto_rawDescGZIP() []byte {
	file_api_grpc_game_game_proto_rawDescOnce.Do(func() {
		file_api_grpc_game_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_game_game_proto_rawDescData)
	})
	return file_api_grpc_game_game_proto_rawDescData
}

var file_api_grpc_game_game_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_grpc_game_game_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_grpc_game_game_proto_goTypes = []interface{}{
	(State)(0),                  // 0: game.State
	(Type)(0),                   // 1: game.Type
	(UnitCode)(0),               // 2: game.UnitCode
	(StreamAction)(0),           // 3: game.StreamAction
	(FinishReason)(0),           // 4: game.FinishReason
	(*CreateGameRequest)(nil),   // 5: game.CreateGameRequest
	(*GameResponse)(nil),        // 6: game.GameResponse
	(*GamePlayerResponse)(nil),  // 7: game.GamePlayerResponse
	(*StreamRequest)(nil),       // 8: game.StreamRequest
	(*StreamResponse)(nil),      // 9: game.StreamResponse
	(*StreamData)(nil),          // 10: game.StreamData
	(*GameStartResponse)(nil),   // 11: game.GameStartResponse
	(*PlayerResponse)(nil),      // 12: game.PlayerResponse
	(*PlayerMoveResponse)(nil),  // 13: game.PlayerMoveResponse
	(*PlayerMovePosition)(nil),  // 14: game.PlayerMovePosition
	(*FinishPlayer)(nil),        // 15: game.FinishPlayer
	(*GameFinishResponse)(nil),  // 16: game.GameFinishResponse
	(*timestamp.Timestamp)(nil), // 17: google.protobuf.Timestamp
	(*any1.Any)(nil),            // 18: google.protobuf.Any
}
var file_api_grpc_game_game_proto_depIdxs = []int32{
	1,  // 0: game.CreateGameRequest.type:type_name -> game.Type
	1,  // 1: game.GameResponse.type:type_name -> game.Type
	0,  // 2: game.GameResponse.state_code:type_name -> game.State
	4,  // 3: game.GameResponse.finish_reason:type_name -> game.FinishReason
	7,  // 4: game.GameResponse.players:type_name -> game.GamePlayerResponse
	17, // 5: game.GameResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 6: game.GameResponse.started_at:type_name -> google.protobuf.Timestamp
	17, // 7: game.GameResponse.finished_at:type_name -> google.protobuf.Timestamp
	3,  // 8: game.StreamRequest.action:type_name -> game.StreamAction
	18, // 9: game.StreamRequest.data:type_name -> google.protobuf.Any
	3,  // 10: game.StreamResponse.action:type_name -> game.StreamAction
	18, // 11: game.StreamResponse.data:type_name -> google.protobuf.Any
	3,  // 12: game.StreamData.action:type_name -> game.StreamAction
	18, // 13: game.StreamData.data:type_name -> google.protobuf.Any
	17, // 14: game.StreamData.ts:type_name -> google.protobuf.Timestamp
	2,  // 15: game.PlayerMoveResponse.unit_code:type_name -> game.UnitCode
	14, // 16: game.PlayerMoveResponse.position:type_name -> game.PlayerMovePosition
	4,  // 17: game.GameFinishResponse.reason:type_name -> game.FinishReason
	15, // 18: game.GameFinishResponse.players:type_name -> game.FinishPlayer
	5,  // 19: game.Service.CreateGame:input_type -> game.CreateGameRequest
	8,  // 20: game.Service.GameStreaming:input_type -> game.StreamRequest
	6,  // 21: game.Service.CreateGame:output_type -> game.GameResponse
	9,  // 22: game.Service.GameStreaming:output_type -> game.StreamResponse
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_grpc_game_game_proto_init() }
func file_api_grpc_game_game_proto_init() {
	if File_api_grpc_game_game_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_game_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GamePlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameStartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMovePosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishPlayer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_game_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameFinishResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_game_game_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_game_game_proto_goTypes,
		DependencyIndexes: file_api_grpc_game_game_proto_depIdxs,
		EnumInfos:         file_api_grpc_game_game_proto_enumTypes,
		MessageInfos:      file_api_grpc_game_game_proto_msgTypes,
	}.Build()
	File_api_grpc_game_game_proto = out.File
	file_api_grpc_game_game_proto_rawDesc = nil
	file_api_grpc_game_game_proto_goTypes = nil
	file_api_grpc_game_game_proto_depIdxs = nil
}
